### PR TITLE
fix: TileLayer url to import base map

### LINKED ISSUE #36: Add the base map to the census tract map
The census tract map only shows the boundaries of the census tracts, but doesn't show any of the underlying roads or neighborhoods that would allow users to more easily identify which tract is theirs. This task is for adding the base map to the census tract.

### PR DESCRIPTION
**Pull request by kmal808**
Fixing `<TileLayer />` url 
Closes #36 

👀 
hierr-esri-dark-base

hierr-esri-dark-base-zoomed

### CODE REVIEW

**Review by avenmia — CHANGES_REQUESTED** [review]
I found this TileLayer in the react-leaflet docs. Is there a reason to not use this instead? Let me know what you think. It seems to look brighter and have more data as you zoom in.

 <TileLayer
      attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
      url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
    />

**Comment by kmal808** [comment]
One more try on the dark map. I present to you Stramen-Tiles-Toner 
- Brighter
- More data when zoomed in
- Flossy af

_Also increased the map size and gave the heading a little love, if you hate it I'll nuke it. NP_


https://user-images.githubusercontent.com/20919083/219633803-37dd1c44-f3ea-4946-9088-04198db417a0.mp4

**Comment by avenmia** [comment]
Let's do the dark map for now and we can ask them on Monday. I like the increased map size and better title too. If you could make the text white and resolve the merge conflicts, this should be good :thumbsup:

**Comment by kmal808** [comment]
> I found this TileLayer in the react-leaflet docs. Is there a reason to not use this instead? Let me know what you think. It seems to look brighter and have more data as you zoom in.
> 
> ```
>  <TileLayer
>       attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
>       url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
>     />
> ```
> 
> https://react-leaflet.js.org/docs/example-popup-marker/

FYI, I'm not able to merge until this is marked as resolved.

**Review by avenmia — APPROVED** [review]
lgtm :shipit:

**Pull request merged**
